#!/bin/bash
if [ -f "./assets/config.json" ]; then
  docker run --rm -v $PWD/assets:/assets twilight_bot
elif [ ! -f "./assets/config.json" ] && [ -z $1 ]; then
  echo "Missing required variable: please enter your bot token as the first argument"
else
  docker run --rm -d -e BOT_TOKEN=$1 -v $PWD/assets/:/assets twilight_bot
fi
